spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
