server:
  port: 20001

spring:
  application:
    name: gateway-routes
  cloud:
    gateway:
      routes:
      - id: baidu_route
        uri: http://www.baidu.com/
        predicates:
        - Path=/baidu
      - id: feign-service-product_v1
        uri: http://localhost:8021/users
        predicates:
        - Path=/users
        - Weight=feign-service-product, 95
      - id: feign-service-product_v2
        uri: http://localhost:8022/users
        predicates:
        - Path=/users
        - Weight=feign-service-product, 5
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerReadTimeoutSeconds: 10

logging:
  level:
    com.netflix: info
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug