server:
  port: 8001
spring:
  application:
    name: transaction-jta-atomikos
  profiles:
    active: mysql
  jta:
    enabled: true
    atomikos:
      datasource:
        t1:
          xa-properties.url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
          xa-properties.user: root
          xa-properties.password: 12345678
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          unique-resource-name: t1
          max-pool-size: 10
          min-pool-size: 1
          max-lifetime: 10000
          borrow-connection-timeout: 10000
        t2:
          xa-properties.url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
          xa-properties.user: root
          xa-properties.password: 12345678
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          unique-resource-name: t2
          max-pool-size: 10
          min-pool-size: 1
          max-lifetime: 10000
          borrow-connection-timeout: 10000









