server:
  port: 8761
spring:
  application:
    name: eureka-server-basicauth
  security:
    user:
      name: admin
      password: 123456
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  server:
      evictionIntervalTimerInMs: 3000
logging:
  level:
    com.netflix: debug
