server:
  port: 8181

spring:
  application:
    name: feign-service-consumer-ribbon
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerReadTimeoutSeconds: 10

ribbon:
  eager-load:
    enabled: true
    clients: feign-service-product
  ReadTimeout: 60000
  ConnectTimeout: 60000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1

feign-service-product:
  robbin:
    NFLoadBalancerClassName: com.netflix.loadbalancer.BaseLoadBalancer
    NFLoadBalancerPingClassName: com.netflix.loadbalancer.DummyPing
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NIWSServerListFilterClassName: com.netflix.loadbalancer.DefaultNIWSServerListFilter
    ConnectTimeout: 30000
    ReadTimeout: 30000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1


logging:
  level:
    com.netflix: debug