server:
  port: 8090
spring:
  application:
    name: grpc-client
  sleuth:
    sampler:
      probability: 1
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerReadTimeoutSeconds: 10

logging:
  level:
    com.netflix: info
grpc:
  client:
    grpc-server:
      negotiationType: PLAINTEXT


