server:
  port: 8011

spring:
  application:
    name: feign-service-consumer
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerReadTimeoutSeconds: 10

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

logging:
  level:
    com.netflix: debug
    com.eyison.client.GithubClient: debug