server:
  port: 20005

spring:
  application:
    name: gateway-dynamic
  redis:
    cluster:
      maxRedirects: 3
      nodes:
      - localhost:7001
      - localhost:7002
      - localhost:7003
      - localhost:7004
      - localhost:7005
      - localhost:7006
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true


eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerReadTimeoutSeconds: 10

logging:
  level:
    com.netflix: info
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug