server:
  port: 9091

alpha:
  server:
    host: 0.0.0.0
    port: 9090

spring:
  application:
    name: transaction-sega-servicecomb-alpha-server
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
    username: root
    password: 12345678
    schema: classpath:schema-mysql.sql
    initialization-mode: always


