server:
  port: 8762
spring:
  application:
    name: eureka-server
eureka:
  instance:
    preferIpAddress: true
    metadataMap.zone: zone2
  client:
    registerWithEureka: false
    fetchRegistry: false
    region: region-east
    serviceUrl:
      zone1: http://localhost:8761/eureka/
      zone2: http://localhost:8762/eureka/
    availability-zones:
      region-east: zone1,zone2
  server:
    evictionIntervalTimerInMs: 3000
    remoteRegionUrlsWithName:
      region-west: http://localhost:8763/eureka/
logging:
  level:
    com.netflix: debug
