server:
  port: 8761
  ssl:
      enabled: true
      key-store: classpath:cert/server.p12
      key-store-password: torepasswd
      key-store-type: PKCS12
      key-alias: server
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
  server:
      evictionIntervalTimerInMs: 3000
logging:
  level:
    com.netflix: debug
