server:
  port: 8764
spring:
  application:
    name: eureka-server
eureka:
  instance:
    preferIpAddress: true
    metadataMap.zone: zone4
  client:
    registerWithEureka: false
    fetchRegistry: false
    region: region-west
    serviceUrl:
      zone3: http://localhost:8763/eureka/
      zone4: http://localhost:8764/eureka/
    availability-zones:
      region-east: zone3,zone4
  server:
    evictionIntervalTimerInMs: 3000
    remoteRegionUrlsWithName:
      region-east: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: debug
