server:
  port: 20003

spring:
  application:
    name: gateway-swagger
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
          - id: feign-service-product-R1
            uri: lb://feign-service-product-R1
            predicates:
            - Path=/r1/**
            filters:
            - StripPrefix=1
          - id: feign-service-product-R2
            uri: lb://feign-service-product-R2
            predicates:
            - Path=/r2/**
            filters:
            - StripPrefix=1
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 1MB
      location: /
  resources:
    static-locations: classpath:/META-INF/resources

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerReadTimeoutSeconds: 10

logging:
  level:
    com.netflix: info
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug